---
- name: Run the application container
  docker_container:
    name: simple-api
    image: nawfelbouzidi/tp-devops-simple-api
    networks:
      - name: my_app_net
    restart_policy: always
    env:
      DATABASE_HOST: pg_db
      DATABASE_PASSWORD: pwd
