---
- name: Run the application container
  docker_container:
    name: pg_db
    image: nawfelbouzidi/tp-devops-database
    env:
      POSTGRES_PASSWORD=pwd
    networks:
      - name: my_app_net
    restart_policy: always
  
